drop database if exists ecommerce;
create database ecommerce;
use ecommerce;

CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50),
TELEFONE_CELULAR CHAR (11),
ENDERECO VARCHAR (100),
CPF CHAR(11),
EMAIL VARCHAR(50)
);

CREATE TABLE FUNCIONARIO(
ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50),
TELEFONE_CELULAR CHAR (11),
ENDERECO VARCHAR (100),
CPF CHAR(11),
EMAIL VARCHAR(50)
);

CREATE TABLE USUARIO(
ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
USUARIO VARCHAR(50),
SENHA VARCHAR (50),
TIPO CHAR (1)
);

CREATE TABLE PRODUTO(
ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
CODIGO_PRODUTO VARCHAR(30) NOT NULL UNIQUE,
DESCRICAO VARCHAR (100) NOT NULL,
MARCA VARCHAR (50),
UNIDADE CHAR(2),
NOME_IMAGEM VARCHAR(100)
);

CREATE TABLE PRECO_VENDA(
COD_PRODUTO VARCHAR(30),
PRECO_VENDA DECIMAL (19,6),
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO_PRODUTO)
);

CREATE TABLE CUSTO(
DATA DATE,
CODIGO_PRODUTO VARCHAR(30),
CUSTO DECIMAL (19,6),
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO_PRODUTO)
);

CREATE TABLE MOVIMENTO_ESTOQUE(
ID_MOVIMENTO INT PRIMARY KEY AUTO_INCREMENT,
CODIGO_PRODUTO VARCHAR(30) NOT NULL,
TIPO_MOVIMENTO INT(2),
DATA DATE,
DOCUMENTO VARCHAR (10),
QUANTIDADE INT,
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO_PRODUTO)
);

CREATE TABLE ESTOQUE_QUANTIDADE(
CODIGO_PRODUTO VARCHAR(30),
ESTOQUE_ATUAL INT,
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO_PRODUTO)
);

-- -----------------------------------------------------------------------

-- inserção tabela produto
INSERT CLIENTE (NOME,TELEFONE_CELULAR,ENDERECO,CPF,EMAIL)
VALUES
('TESTE CLIENTE', '41111111111', 'RUA TESTE', '11122233344', 'TESTE.CLIENTE@TESTE.COM');
INSERT FUNCIONARIO (NOME,TELEFONE_CELULAR,ENDERECO,CPF,EMAIL)
VALUES
('TESTE FUNCIONARIO', '41111111111', 'RUA TESTE', '11122233344', 'TESTE.FUNCIONARIO@TESTE.COM');
INSERT USUARIO (USUARIO,SENHA,TIPO)
VALUES
('ADMIN', 'ADMIN', 'A');
INSERT PRODUTO (CODIGO_PRODUTO,DESCRICAO,MARCA,UNIDADE, NOME_IMAGEM)
VALUES 
(00001,'WHEY PROTEIN 500G BAUNILHA','BULL SKILL','UN', 'WHEY-PROTEIN-500G-BAUNILHA.jpg'),
(00002,'WHEY PROTEIN 500G CHOCOLATE','BULL SKILL','UN', 'WHEY-PROTEIN-500G-CHOCOLATE.jpg'),
(00003,'CREATINA EM PÓ 50G','GROWTH','UN', 'CREATINA-EM-PO-50G.jpg'),
(00004,'CREATINA EM PÓ 1000G','GROWTH','UN', 'CREATINA-EM-PO-1000G.jpg'),
(00005,'CREATINA EM CAPSULA 60UN','INTEGRAL MEDICA','UN', 'CREATINA-EM-CAPSULA-60UN.jpg'),
(00006,'CREATINA EM CAPSULA 180UN','INTEGRAL MEDICA','V', 'CREATINA-EM-CAPSULA-180UN.jpg'),
(00007,'BCAA EM PÓ 50G','MAX TITANIUM','UN', 'BCAA-EM-PO-50G.jpg'),
(00008,'BCAA EM PÓ 100G','MAX TITANIUM','UN', 'BCAA-EM-PO-100G.jpg'),
(00009,'BCAA EM CAPSULA 60UN','PROBIOTICA','UN', 'BCAA-EM-CAPSULA-60UN.jpg'),
(00010,'BCAA EM CAPSULA 120UN','PROBIOTICA','UN', 'BCAA-EM-CAPSULA-120UN.jpg'),
(00011,'PASTA DE AMENDOIN','PROBIOTICA','UN', 'PASTA-DE-AMENDOIN.jpg'),
(00012,'GLUTAMINA','PROBIOTICA','UN', 'GLUTAMINA.jpg');

CREATE USER 'thebugs'@'localhost' IDENTIFIED BY 'thebugs';
GRANT ALL PRIVILEGES ON * . * TO 'thebugs'@'localhost';
FLUSH PRIVILEGES;